name: Set up Terraform

on:
    push:
        branches:
            - master

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform init
              env:
                  TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  TF_VAR_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  TF_VAR_GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                  TF_VAR_GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
              run: terraform init

            - name: Terraform plan
              env:
                  TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  TF_VAR_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  TF_VAR_GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                  TF_VAR_GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
              run: |
                  terraform plan -input=false

            - name: Terraform apply
              env:
                  TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
                  TF_VAR_ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  TF_VAR_ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  TF_VAR_GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                  TF_VAR_GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
              run: |
                  az login --service-principal --username $TF_VAR_ARM_CLIENT_ID --password $TF_VAR_ARM_CLIENT_SECRET --tenant $TF_VAR_ARM_TENANT_ID
                  terraform import -input=false azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-rg
                  terraform import -input=false azurerm_virtual_network.vnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-vnet
                  terraform import -input=false azurerm_subnet.subnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-subnet
                  terraform import -input=false azurerm_public_ip.public_ip /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-public-ip
                  terraform import -input=false azurerm_network_interface.nic /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-nic
                  terraform import -input=false azurerm_network_security_group.nsg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-nsg
                  terraform import -input=false azurerm_linux_virtual_machine.vm /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/nodeapp-vm


                  terraform apply -input=false -auto-approve
